language: php

php:
  - 7.0
  - 7.1

before_script:
  - phpenv config-rm xdebug.ini
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev
  - travis_retry composer self-update

script:
  - vendor/bin/phpunit

cache:
  directories:
    - node_modules
    - vendor
