language: php

php:
  - 7.0
  - 7.1

sudo: false

before_install:
  - phpenv config-rm xdebug.ini

install:
  - travis_retry composer install --no-interaction --prefer-source --no-suggest

script:
  - $TRAVIS_BUILD_DIR/vendor/bin/phpunit

