language: php

php:
  - 7.3
  - 7.4

env:
  global:
    - CC_TEST_REPORTER_ID=$CODECLIMATE_REPO_TOKEN
  matrix:
    - LARAVEL_VERSION=5.8.*
    - LARAVEL_VERSION=6.*
    - LARAVEL_VERSION=7.*
    - LARAVEL_VERSION=8.*

matrix:
  fast_finish: true

sudo: false

install:
  - if [ "$LARAVEL_VERSION" != "" ]; then composer require --dev "laravel/framework:${LARAVEL_VERSION}" --no-update; fi;
  - travis_retry composer install --no-interaction --prefer-source --no-suggest

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - $TRAVIS_BUILD_DIR/vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT;
