script: phpunit

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev
  - travis_retry composer self-update
