language: php

php:
  - 7.1
  - 7.2

sudo: false

install:
  - travis_retry composer install --no-interaction --prefer-source --no-suggest

script:
  - $TRAVIS_BUILD_DIR/vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN ./vendor/bin/test-reporter
